# Config file for air
# https://github.com/cosmtrek/air

root = "/app"
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/server"
bin = "tmp/main"
bin_windows = "tmp/main.exe"
full_bin = "app/tmp/main"

[watch]
# Directories to watch for changes
includes = ["cmd/", "pkg/", "internal/", "main.go", "go.mod"]
# File extensions to watch
extensions = [".go", ".tpl", ".html"]

# [dev]
# # Log level
# log_level = "debug"
# # The delimiter used to identify the file extension
# extension_delimiter = "."

# [log]
# # The color mode of the logger output, one of 'off', 'nocolor', 'auto', 'force'
# color = "auto"
# # The color mode of the logger output, one of 'off', 'on'
# timestamp = "on"

# [hot]
# # Use polling instead of fsnotify
# polling = false
# # Delay for restarting after changes (in milliseconds)
# interval = 1000

# [args]
# # Additional arguments for the binary
# bin_args = []

# [env]
# # Additional environment variables for the binary
# BIN_ENV = "dev"
