version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8081"

  development:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT}:8081"
    volumes:
      - .:/app
  
  # swagger:
  #   image: ghcr.io/swaggo/swag:latest
  #   volumes:
  #     - .:/code
  #   command: "init"
