version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "${PORT}:8081"

  development:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "${PORT}:8081"
    volumes:
      - ./:/app

  swagger:
    build:
      context: .
      dockerfile: docker/Dockerfile.swagger
    volumes:
      - ./:/app