FROM golang:1.22.4-alpine

RUN apk update && apk add --no-cache git

RUN go install github.com/cosmtrek/air@v1.0.1

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
